FROM golang AS plugin
RUN mkdir -p /go/src/github.com/alfred-landrum/docker-metrics-plugin-test
COPY . /go/src/github.com/alfred-landrum/docker-metrics-plugin-test
RUN cd /go/src/github.com/alfred-landrum/docker-metrics-plugin-test  && go get && CGO_ENABLED=0 go build -tags netgo -o metrics
RUN mkdir -p /run/docker

FROM alpine:3.5
RUN apk add --no-cache ca-certificates
COPY --from=plugin /go/src/github.com/alfred-landrum/docker-metrics-plugin-test/metrics /
COPY --from=plugin /run/docker /run/docker
ENTRYPOINT ["/metrics"]
